canonical/kserve-operators

charms/kserve-web-app/config.yaml
This fixes the kserve-model-web-app by using the correct port (5000) for the web application.  As far as I can tell, this is not configurable at the application level, so probably config.port can be removed entirely. 
To test:
```
charmcraft pack
juju deploy ./kserve-web-app_ubuntu-20.04-amd64.charm --resource kserve-web-app-image=kserve/models-web-app:v0.8.0
juju deploy istio-pilot --trust --channel 1.11/stable --config default-gateway=my-gateway
juju deploy istio-gateway istio-ingressgateway --trust --channel 1.11/stable --config kind=ingress
juju relate istio-pilot istio-ingressgateway
```
Now you should be able to browse to the following:
* unitIP:5000
* serviceIP:5000
But for some reason (not sure why?  something to do with the way the app is coded maybe?) those will show as blank …
=> fix: Set config.port to match web-app's exposed port

.github/workflows/integrate.yaml, .github/workflows/on_pull_request.yaml, .github/workflows/on_push.yaml, tox.ini
In this PR:
* tox.ini is added defining how to run lint, unit, and integration tests. Regarding the latter, only the individual charm's integration tests will be run as integration between web-app and controller hasn't been added.
* Integration job inside on pull/push yaml files is renamed to `integrate.yaml`
=> ci: enable lint, unit and integration tests

charms/kserve-controller/tests/unit/test_charm.py
We need to set_can_connect in order to access containers and pebble related objects. Prevents the following from happening:
```
ops.pebble.ConnectionError: Cannot connect to Pebble; did you forget to call begin_with_initial_hooks() or set_can_connect()?
```
=> tests: add set_can_connect to harness for testing pebble related objects

.github/workflows/get-charm-paths.sh, .github/workflows/on_pull_request.yaml, .github/workflows/publish.yaml
This publish job replaces the older one with the standard reusable publish job in all Charmed Kubeflow repositories.
Dear reviewer: the publish job for kserve-web-app is expected to fail as the charm is not ready yet. We can safely ignore it.
=> ci: add reusable publish job

.github/workflows/integrate.yaml, charms/kserve-controller/src/charm.py, charms/kserve-controller/tests/integration/sklearn-iris.yaml, charms/kserve-controller/tests/integration/test_charm.py, charms/kserve-controller/tests/unit/test_charm.py
Restarting the service ensures it catches new configurations.
Dear reviewer(s), please note this PR also includes small fixes to the CI and integration tests to unblock them. If you think they belong in a different PR, let me know.
Fixes #103, #105
=> fix: restart kserve-controller service on config changed

charms/kserve-controller/tox.ini, tox.ini
Updates tox.ini's `update-requirements` as described in https://github.com/canonical/argo-operators/pull/100
=> update tox.ini's update-requirements

.github/workflows/get-charm-paths.sh
fix: ported fix for failing charm publish
Details are in: https://github.com/canonical/kserve-operators/issues/156
- Updated workflow not to include kserve-web-app charm in list of charms for publishing.
NOTE: This PR is porting fix that was done on `main` into `tracjk/0.10`. Refer to the issue linked to this PR for more details.
=> Kf 4223 fix do not publish kserve web app charm

tools/get-images.sh
`kserve-web-app` is not deployed as part of 1.7 release. Get images script incorrectly retrieves image from `kserve-web-app` charm which incorrectly shows up on report of deployable images.
This changes will address the issue by only scanning charm that is deployed in 1.7 release.
More details are in https://github.com/canonical/bundle-kubeflow/issues/674
- Modified script to retrieve images only from kserve-controller, because kserve-web-app is not deployed in this release.
NOTE: This change is only applicable to track/0.10
=> fix: modified to retrieve images only from one charm

charms/kserve-controller/src/charm.py
For 3 of the images (i.e. explainers), the charm attempts to separate the image name from the tag, splitting the string in two using `:` as a separator. However, this breaks the installation if the image name contains that special character, which could be the case if a local container registry address is provided for instance (e.g. `172.17.0.2:5000/kserve/alibi-explainer:latest`).
Use `rsplit` to ensure that the rightmost part of the string (following the last `:`) is parsed as the tag.
Closes #159
=> fix: Parse custom images with ":" in their name

tools/get-images.sh
Details on the issue and design are in: https://github.com/canonical/kserve-operators/issues/162
- Added scrip to retrieve images referenced in kserve
NOTE: This PR should be merged after https://github.com/canonical/kserve-operators/pull/163
=> fix: get images on main

charms/kserve-controller/config.yaml, charms/kserve-controller/tests/integration/test_charm.py
Set default config to `serverless`. 
In integration tests we first run tests for `rawdeployment` mode and then the tests set the `serverless` config.
=> Run kserve-controller in serverless mode by default

charms/kserve-controller/src/default-custom-images.json
- Bump version of mlserver to 1.3.5 to have image with less CVEs.
=> fix: bump mlserver version to 1.3.5

charms/kserve-controller/metadata.yaml, charms/kserve-controller/requirements-fmt.txt, charms/kserve-controller/requirements-integration.in, charms/kserve-controller/requirements-integration.txt, charms/kserve-controller/requirements-lint.txt, charms/kserve-controller/requirements-unit.txt, charms/kserve-controller/requirements.in, charms/kserve-controller/requirements.txt, charms/kserve-controller/src/charm.py, charms/kserve-controller/src/secrets/kserve-mlflow-minio-secret.yaml.j2, charms/kserve-controller/src/service-accounts/kserve-mlflow-minio-svc-account.yaml.j2, charms/kserve-controller/tests/integration/crds/poddefaults.yaml, charms/kserve-controller/tests/integration/namespace.yaml, charms/kserve-controller/tests/integration/test_charm.py, charms/kserve-controller/tests/test_data/secret.yaml.j2, charms/kserve-controller/tests/test_data/service-account-yaml.j2, charms/kserve-controller/tests/unit/test_charm.py
Kserve now can be integrated with resource dispatcher to be able to serve models from MLflow. In order to do that following manifests need to be created in user namespaces (secret and svc abbount with credentials to connect to object store) https://kserve.github.io/website/0.11/modelserving/storage/s3/s3/#deploy-the-model-on-s3-with-inferenceservice 
This PR:
- allows kserve to relate to minio (this is optional relation because kserve can work also without it).
- sends secrets and service accounts to resource dispatcher through relations
Integration tests are deploying metacontroller, poddefaults crd minio and resource dispatcher to simulate the usecase. An example labeled user namespace is created and the test check that the user manifests are created.
=> Integrate with resource dispatcher

charms/kserve-controller/src/charm.py, charms/kserve-controller/tests/integration/test_charm.py, charms/kserve-controller/tests/unit/test_charm.py
Refactors the `kserve-controller` charm to have an `on_event` event handler that handles events with common behavior.
fixes #194
=> fix: use an all-catch main event handler

.github/workflows/integrate.yaml
By default, Juju automatically retries any failed hook (any event that raises an uncaught exception).  This is often helpful, but in our CI it might hide transient errors that we would want to fix.  We should disable this behavior in our test environment.
closes #202 
should be merged after #203
=> ci: set automatically-retry-hooks to false

charms/kserve-controller/src/default-custom-images.json, charms/kserve-controller/tests/integration/test_charm.py
=> integrate pmmlserver rock for 0.11.2

charms/kserve-controller/src/default-custom-images.json, charms/kserve-controller/tests/integration/test_charm.py, charms/kserve-controller/tests/integration/xgbserver.yaml
=> Integrate rock for xgbserver v0.11.2

charms/kserve-controller/tests/integration/test_charm.py
Because charms in latest/edge change often and the 0.11 version of kserve was initially tested using different versions of charms (metacontroller, minio, resource dispatcher), we need to ensure this testing environment is kept as it was back then. Pinning those dependencies to the right version to avoid future isssues.
=> tests: pin charm dependencies to stable channels that correspond to CKF 1.8

charms/kserve-controller/metadata.yaml
closes #213 
uses the rock published from the on push of PR https://github.com/canonical/kserve-rocks/pull/48
=> feat: Integrate rock for controller v0.11.2

charms/kserve-controller/src/default-custom-images.json, charms/kserve-controller/tests/integration/config-map-data-changed.yaml, charms/kserve-controller/tests/integration/config-map-data.yaml
cherry-picks 63d853893274ec59f1d647cc304f9762896b2baa to `track/0.11`
=> feat: use agent rock v0.11.2 (#226)

charms/kserve-controller/config.yaml, charms/kserve-controller/metadata.yaml, charms/kserve-controller/src/charm.py, charms/kserve-controller/src/default-custom-images.json, charms/kserve-controller/src/templates/cluster_storage_containers.yaml.j2, charms/kserve-controller/src/templates/configmap_manifests.yaml.j2, charms/kserve-controller/src/templates/crd_manifests.yaml.j2, charms/kserve-controller/src/templates/serving_runtimes_manifests.yaml.j2, charms/kserve-controller/src/templates/webhook_manifests.yaml.j2, charms/kserve-controller/tests/integration/config-map-data-changed.yaml, charms/kserve-controller/tests/integration/config-map-data.yaml
closes: https://github.com/canonical/kserve-operators/issues/233
Changes from https://github.com/kubeflow/manifests. Comparing tags `v1.8.0` and `v1.9.0-rc.0`
Key changes: 
- added `huggungface` runtime 
- new `ClusterStorageContainer` `default` object
- few new `storageInitializer` config options
to not derail the task I have created [enhancement task](https://github.com/canonical/kserve-operators/issues/235) for the `huggingface` integration test.
=> chore: change manifests  0.11.2 -> 0.12.1

.github/workflows/integrate.yaml, charms/kserve-controller/config.yaml, charms/kserve-controller/metadata.yaml, charms/kserve-controller/src/charm.py, charms/kserve-controller/src/default-custom-images.json, charms/kserve-controller/src/templates/auth_manifests.yaml.j2, charms/kserve-controller/src/templates/configmap_manifests.yaml.j2, charms/kserve-controller/src/templates/crd_manifests.yaml.j2, charms/kserve-controller/tests/integration/config-map-data-changed.yaml, charms/kserve-controller/tests/integration/config-map-data.yaml, charms/kserve-controller/tests/integration/test_charm.py
Closes: https://github.com/canonical/kserve-operators/issues/238
Compared kustomize output for tags `v0.12.1` and `v0.13.0` for these upstream files https://github.com/kserve/kserve/tree/v0.13.0/config/overlays/kubeflow.
Changes: 
- Removing alibi server 
- Minor crd changes by adding deploymentStrategy
- Removing conversion webhook strategy
- Updating images
=> Update manifests for v0.13.0

.github/workflows/integrate.yaml
Part of canonical/bundle-kubeflow#944
=> ci: use juju 3.4/stable instead of 3.5/stable in track 0.11

charms/kserve-controller/src/charm.py, charms/kserve-controller/tests/integration/test_charm.py, charms/kserve-controller/tests/unit/test_charm.py
* feat: refactor to main event handler
* feat: unit test no relation to knative
* fix: write missing controller ready active unit test
This cherry-pick fixes #242. For details on why this is the case as well as detailed reproduce & testing instructions, take a look at https://github.com/canonical/kserve-operators/issues/242#issuecomment-2205927337.
Closes #242, #176, #229
=> cherry-pick(fix): use an all-catch event handler (#197)

charms/kserve-controller/lib/charms/loki_k8s/v1/loki_push_api.py, charms/kserve-controller/metadata.yaml, charms/kserve-controller/requirements-integration.in, charms/kserve-controller/requirements-integration.txt, charms/kserve-controller/requirements-unit.txt, charms/kserve-controller/requirements.in, charms/kserve-controller/requirements.txt, charms/kserve-controller/src/charm.py, charms/kserve-controller/tests/integration/test_charm.py, charms/kserve-controller/tests/unit/test_charm.py
Use LogForwarder from loki_push_api library to forwards all logs from workload container to Loki. This requires to use ops 2.9 or newer, so it was needed to be updated.
fixes: #236
How I tested it:
```bash
$ tox -e integration -- --keep-models
$ juju switch test-charm-kee3
$ juju consume u1-k8s:cos.loki-logging 
Added u1-k8s:admin/cos.loki-logging as loki-logging
$ juju integrate grafana-agent-k8s loki-logging
$ juju config kserve-controller custom_images=@custom_images
```
And after checking the Grafana, I was able to see all logs.
=> Add logging relation to kserve-controller

.github/workflows/publish.yaml
Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993
=> ci(upload-charm): use charmcraft from latest/candidate in track/0.13

charms/kserve-controller/config.yaml, charms/kserve-controller/src/charm.py, charms/kserve-controller/src/templates/cluster_storage_containers.yaml.j2, charms/kserve-controller/tests/integration/test_charm.py
* backports #257 to `track/0.11`
* adds `ClusterStorageContainer` CR to the charm k8s resources as part of the backport
1. Deploy the following bundle:
```
bundle: kubernetes
name: kubeflow
docs: https://discourse.charmhub.io/t/3749
applications:
istio-ingressgateway:
charm: istio-gateway
channel: 1.17/stable
scale: 1
trust: true
_github_repo_name: istio-operators
_github_repo_branch: track/1.17
options:
kind: ingress
istio-pilot:
charm: istio-pilot
channel: 1.17/stable
scale: 1
trust: true
_github_repo_name: istio-operators
_github_repo_branch: track/1.17
options:
default-gateway: kubeflow-gateway
knative-eventing:
charm: knative-eventing
channel: 1.10/stable
scale: 1
trust: true
options:
namespace: knative-eventing
_github_repo_name: knative-operators
_github_repo_branch: track/1.10 …
```
=> (cherry-pick to track/0.11) fix: configure proxy env vars storage init container (#257)

charms/kserve-controller/src/prometheus_alert_rules/KubeflowKserveControllerServices.rules, charms/kserve-controller/tests/integration/test_charm.py
These alert rules provide an overview of all service states.
Using the KubeflowServiceDown or KubeflowServiceIsNotStable filter, the user
can easily see the status of all Kubeflow services.
These changes can be tested by running the following commands:
```bash
tox -e integration -- --keep-models
juju -m <model-name> show-unit grafana-agent-k8s/0 --endpoint metrics-endpoint | yq '.[]."relation-info".[]."application-data".alert_rules | fromjson'
juju consume <controller>:cos.remote-write
juju integrate remote-write grafana-agent-k8s
kubectl exec -it -n <model-name> pod/<pod-name> -c <workload-container> -- /charm/bin/pebble start <service-name>
```
part-of: [#1026](https://github.com/canonical/bundle-kubeflow/issues/1026)
=> Add alert rules to kserve-controller based on the KF093 spec

charms/kserve-controller/config.yaml, charms/kserve-controller/src/charm.py, charms/kserve-controller/src/templates/cluster_storage_containers.yaml.j2, charms/kserve-controller/tests/integration/test_charm.py
backports #257 to `track/0.13`
1. Deploy the following bundle:
```
bundle: kubernetes
name: kubeflow
docs: https://discourse.charmhub.io/t/3749
applications:
istio-ingressgateway:
charm: istio-gateway
channel: 1.22/stable
scale: 1
trust: true
_github_repo_name: istio-operators
_github_repo_branch: main
options:
kind: ingress
istio-pilot:
charm: istio-pilot
channel: 1.22/stable
scale: 1
trust: true
_github_repo_name: istio-operators
_github_repo_branch: main
options:
default-gateway: kubeflow-gateway
knative-operator:
charm: knative-operator
channel: 1.12/stable
scale: 1
trust: true
_github_repo_name: knative-operators
_github_repo_branch: main
knative-serving:
charm: knative-serving
channel: 1.12/stable
scale: 1
trust: true
options:
namespace: knative-serving
istio.gateway.namespace: …
```
=> (cherry-pick to track/0.13) fix: configure proxy env vars storage init container (#257)

.github/workflows/publish.yaml
Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993
=> ci(upload-charm): use charmcraft from latest/candidate in track/0.11

.github/workflows/integrate.yaml, .gitignore, charms/kserve-controller/terraform/README.md, charms/kserve-controller/terraform/main.tf, charms/kserve-controller/terraform/outputs.tf, charms/kserve-controller/terraform/variables.tf, charms/kserve-controller/terraform/versions.tf, charms/kserve-controller/tox.ini
Ref: #270.
This PR creates a `terraform/` directory in each charm that hosts the Terraform module. It follows the structure proposed in [this spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit).
To test the module:
- Clone the repository and switch to this branch.
- First run `tox -e tflint` to ensure that linting is correct
- Change to the `terraform/` directory and run `terraform init`.
- Run `terraform apply -var "channel=latest/edge" -var "model_name=kubeflow" --auto-approve` and wait until the charm is `Active` and `Idle`.
=> Feat: Add Terraform module

.github/workflows/integrate.yaml, .gitignore, charms/kserve-controller/terraform/README.md, charms/kserve-controller/terraform/main.tf, charms/kserve-controller/terraform/outputs.tf, charms/kserve-controller/terraform/variables.tf, charms/kserve-controller/terraform/versions.tf, charms/kserve-controller/tox.ini
Ref: #270 
This is a backport to create a Terraform module in the `terraform` directory. It follows the structure proposed in [this spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit).
To test the module:
- Clone the repository and switch to this branch.
- First run `tox -e tflint` to ensure that linting is correct
- Change to the `terraform/` directory and run `terraform init`.
- Run `terraform apply -var "channel=0.13/stable" -var "model_name=kubeflow" --auto-approve` and wait until the charm is `Active` and `Idle`.
=> (backport) Feat: Add Terraform module

charms/kserve-controller/src/prometheus_alert_rules/KubeflowKserveControllerServices.rules, charms/kserve-controller/tests/integration/test_charm.py
Part of: https://github.com/canonical/bundle-kubeflow/issues/1109
* Add alert rules to kserve-controller based on the KF093 spec
* add cos integration tests for alert rules
=> Backport: Add alert rules to kserve-controller based on the KF093 spec (#265)

charms/kserve-controller/src/default-custom-images.json, charms/kserve-controller/tests/integration/config-map-data-changed.yaml, charms/kserve-controller/tests/integration/config-map-data.yaml
closes https://github.com/canonical/kserve-rocks/issues/95
replaces the `kserve-agent` rock with the patch from https://github.com/canonical/kserve-rocks/pull/98
=> fix: integrate `kserve-agent` rock with patch

charms/kserve-controller/requirements-fmt.txt, charms/kserve-controller/requirements-integration.txt, charms/kserve-controller/requirements-lint.txt, charms/kserve-controller/requirements-unit.txt, charms/kserve-controller/requirements.txt, charms/kserve-controller/tox.ini, tox.ini
* Pin pip to 24.2 due to https://github.com/jazzband/pip-tools/issues/2131
* Update python dependencies using 'tox -e update-requirements'
Ref canonical/bundle-kubeflow#1177
=> chore: update python dependencies + pin pip

charms/kserve-controller/CONTRIBUTING.md, charms/kserve-controller/README.md, charms/kserve-controller/metadata.yaml, charms/kserve-controller/src/charm.py, charms/kserve-controller/tests/integration/test_charm.py, charms/kserve-controller/tests/unit/test_charm.py
Closes: https://github.com/canonical/kserve-operators/issues/287
This PR removes the rbac proxy layer from the charm. This is possible as kubeflow-rbac-proxy was not intercepting the traffic.
=> Remove rbac proxy layer

charms/kserve-controller/lib/charms/resource_dispatcher/v0/kubernetes_manifests.py
This repository contained a version of the kubernetes_manifestss lib that was not exactly the one that was published in Charmhub. This caused issues when trying to fetch new versions of the library.
This commit replaces the offending file with the library that is actually published.
Part of canonical/bundle-kubeflow#1209
=> fix: fetch kubernetes_manifests lib with charmcraft to match published lib

charms/kserve-controller/src/default-custom-images.json
This PR integrates the latest version of the pmmlserver rock, that was published in https://github.com/canonical/kserve-rocks/actions/runs/13261534027/job/37019834883
=> Integrate pmmlserver rock v0.14

charms/kserve-controller/src/default-custom-images.json, charms/kserve-controller/tests/integration/config-map-data-changed.yaml, charms/kserve-controller/tests/integration/config-map-data.yaml
closing [KF-6961](https://warthogs.atlassian.net/browse/KF-6961)
[KF-6961]: https://warthogs.atlassian.net/browse/KF-6961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: bump version to 0.14.1-397d028

charms/kserve-controller/src/default-custom-images.json
This PR integrates the `sklearnserver` rock into the default custom images. The rock was published by [this action](https://github.com/canonical/kserve-rocks/actions/runs/13285101008/job/37092887881).
=> chore: integrate sklearnserver rock v0.14.1

charms/kserve-controller/src/charm.py, charms/kserve-controller/src/default-custom-images.json, charms/kserve-controller/src/templates/webhook_manifests.yaml.j2, charms/kserve-controller/tests/unit/test_charm.py
Closes https://github.com/canonical/kserve-operators/issues/301
1. Adds pebble readiness and liveness probes for KServe Controller (workload service)
2. Creates a separate resource handler for applying `ClusterServingRuntimes` separately
3. Gracefully handles `connection refused` errors, when applying the `ClusterServingRuntimes`
- I noticed that we don't handle the `update-status` event at all in the KServe controller
- In `kfp-api` we have a [dedicated handler](https://github.com/canonical/kfp-operators/blob/53b7e82f2625c17af994f124aefc229c2dd7f9ee/charms/kfp-api/src/charm.py#L108) for `update-status` that [checks the probes status](https://github.com/canonical/kfp-operators/blob/53b7e82f2625c17af994f124aefc229c2dd7f9ee/charms/kfp-api/src/charm.py#L314-L332)
- I didn't add it as the …
=> fix: Add missing ClusterServingRuntime validation webhook

charms/kserve-controller/src/charm.py, charms/kserve-controller/tests/integration/test_charm.py
Closes #321 #319
Handles applying the `ClusterServingRuntime` (CSR) resources errors by:
1. Moving starting the pebble service (i.e. calling `update_layer` for the first time) to run before attempting to apply the CSRs, this is essential for the kserve controller to be up which serves the webhook
2. Putting the charm to Maintenance and skip applying the CSRs on the known error messages that are expected during startup, this includes `connection refused` and `no endpoints available` errors.
3. Observing the `update_status` event so that it triggers the charm reconciliation after the update status interval, the webhook server should be up by then.
1. Deploy `latest/edge` bundle on AKS [guide](https://charmed-kubeflow.io/docs/install-on-aks)
4. `kserve-controller` charm goes to Blocked
5. …
=> fix: handle validating webhook unreachable errors

charms/kserve-controller/tests/integration/test_charm.py
Pin charms-dependencies according to 1.10/stable bundle.
Close https://warthogs.atlassian.net/browse/KF-7233
=> chore(tests): Pin charms-dependencies

charms/kserve-controller/src/default-custom-images.json
Cherry-picks 9e829da from `main`
https://github.com/canonical/kserve-operators/pull/344
=> backport(feat): integrate rock for torchserve-kfs

charms/kserve-controller/requirements-integration.txt, charms/kserve-controller/tests/integration/charms_dependencies.py, charms/kserve-controller/tests/integration/test_charm.py
Move dependency charms deployed during tests to a separate file called
charms_dependencies.py. This enables programmatic access to them and
thus updating them centrally, probably with the use of `kfcicli`. This
uses the `CharmSpec` dataclass from chisme.
Ref canonical/bundle-kubeflow/issues/1256
=> refactor(tests): Move dependency charms to a separate file

charms/kserve-controller/tests/integration/test_charm.py
Closes #379 
This PR simply removes the `namespace` config option when deploying `knative-serving` in the integration tests. This follows the removal of the option in https://github.com/canonical/knative-operators/pull/356
=> fix: Remove namespace config from `knative-serving` in integration tests
