canonical/kserve-operators

- .github/workflows/integration.yaml
- .github/workflows/publish.yaml
- .github/workflows/release.yaml
git-xargs programmatic pull request
> fix: bump charming-actions to v2.1.1

- README.md
Add RawDeployment instructions
> docs: add kserve deployment instructions

- README.md
- charms/kserve-controller/.gitignore
- charms/kserve-controller/.jujuignore
- charms/kserve-controller/LICENSE
- charms/kserve-controller/README.md
- charms/kserve-controller/charmcraft.yaml
- charms/kserve-controller/config.yaml
- charms/kserve-controller/metadata.yaml
- charms/kserve-controller/pyproject.toml
- charms/kserve-controller/requirements-fmt.txt
- charms/kserve-controller/requirements-integration.txt
- charms/kserve-controller/requirements-lint.txt
- charms/kserve-controller/requirements-unit.txt
- charms/kserve-controller/requirements.txt
- charms/kserve-controller/src/charm.py
- charms/kserve-controller/src/templates/auth_manifests.yaml.j2
- charms/kserve-controller/src/templates/configmap_manifests.yaml.j2
- charms/kserve-controller/src/templates/crd_manifests.yaml.j2
- charms/kserve-controller/src/templates/serving_runtimes_manifests.yaml.j2
- charms/kserve-controller/src/templates/webhook_manifests.yaml.j2
- charms/kserve-controller/tests/integration/test_charm.py
- charms/kserve-controller/tests/unit/test_charm.py
- charms/kserve-controller/tox.ini
All changes in this branch have already been reviewed and approved in #9 and #10. This is an attempt to merge those commits into main.
> Merge dev branch into main

- charms/kserve-controller/src/charm.py
- charms/kserve-controller/tests/unit/test_charm.py
This PR fixes all [errors](https://github.com/canonical/kserve-operators/actions/runs/4001071682/jobs/6866923121) in the CI of #43. 
Dear reviewer: Please note this branch is based on `main` and the CI that actually adds the lint, unit, and integration jobs is going to be added in #43, thus this PR should be merged after that one. Errors in this PR's CI are expected until we merge that other PR.
> refactor: fix linting and format errors

- .github/workflows/issues_to_jira.yaml
ci: add jira automation to create GH issues as jira card
> ci: add jira automation to create GH issues as jira card

- README.md
> docs: fix faulty instructions for RawDeployment

- README.md
Add instructions for serverless and expand rawdeployment mode.
> docs: add instructions for serverless and expand rawmdeployment mode

- charms/kserve-controller/src/charm.py
- charms/kserve-controller/src/default-custom-images.json
Details on the issue and design are in: https://github.com/canonical/kserve-operators/issues/161
- Moved images list into separate file and modified code to load it from that file.
> fix: redesign default images handling

- charms/kserve-controller/src/default-custom-images.json
- charms/kserve-controller/src/templates/serving_runtimes_manifests.yaml.j2
- charms/kserve-controller/tests/integration/pmml-server.yaml
- charms/kserve-controller/tests/integration/test_charm.py
Use pmml rock as default image
Adjust pmml runtime
Add integration test
> Use pmml rock

- README.md
This will ensure that we comply with the expectations in https://releases.juju.is/?team=MLOps
> Add badges to repo

- .gitignore
- README.md
- charms/kserve-controller/src/default-custom-images.json
- charms/kserve-controller/tests/integration/paddleserver-resnet.yaml
- charms/kserve-controller/tests/integration/test_charm.py
> KF 5328 integrate paddleserver rock

- README.md
- charms/kserve-controller/src/default-custom-images.json
- charms/kserve-controller/tests/integration/config-map-data-changed.yaml
- charms/kserve-controller/tests/integration/config-map-data.yaml
> integrate storage-initializer rock

- charms/kserve-controller/src/default-custom-images.json
- charms/kserve-controller/tests/integration/lgbserver.yaml
- charms/kserve-controller/tests/integration/test_charm.py
> Integrate rock for lgbserver v0.11.2

- .gitignore
- README.md
- charms/kserve-controller/src/default-custom-images.json
- charms/kserve-controller/tests/integration/config-map-data-changed.yaml
- charms/kserve-controller/tests/integration/config-map-data.yaml
- charms/kserve-controller/tests/integration/lgbserver.yaml
- charms/kserve-controller/tests/integration/paddleserver-resnet.yaml
- charms/kserve-controller/tests/integration/sklearn-iris.yaml
- charms/kserve-controller/tests/integration/test_charm.py
- charms/kserve-controller/tests/integration/xgbserver.yaml
Cherry-picking the following PRs:
- https://github.com/canonical/kserve-operators/pull/219
- https://github.com/canonical/kserve-operators/pull/217
- https://github.com/canonical/kserve-operators/pull/209
- https://github.com/canonical/kserve-operators/pull/218
- https://github.com/canonical/kserve-operators/pull/221
- https://github.com/canonical/kserve-operators/pull/222
> Cherry pick ROCKs to the track/0.11

- charms/kserve-controller/src/default-custom-images.json
- charms/kserve-controller/tests/integration/config-map-data-changed.yaml
- charms/kserve-controller/tests/integration/config-map-data.yaml
closes #214 
uses the rock published from the on push of PR https://github.com/canonical/kserve-rocks/pull/49
> Integrate rock for agent v0.11.2

- charms/kserve-controller/metadata.yaml
cherry-picks d57f34fe18d06908637561e81f56a72835422a29 to `track/0.11`
> feat: use controller rock v0.11.2 (#225)

- charms/kserve-controller/requirements-integration.txt
- charms/kserve-controller/requirements-unit.txt
- charms/kserve-controller/requirements.txt
Part of canonical/bundle-kubeflow#868
> build: bump ops to latest possible version

- charms/kserve-controller/metadata.yaml
- charms/kserve-controller/src/default-custom-images.json
- charms/kserve-controller/tests/integration/config-map-data-changed.yaml
- charms/kserve-controller/tests/integration/config-map-data.yaml
Closes:
https://github.com/canonical/kserve-rocks/issues/67
https://github.com/canonical/kserve-rocks/issues/68
https://github.com/canonical/kserve-rocks/issues/69
https://github.com/canonical/kserve-rocks/issues/70
https://github.com/canonical/kserve-rocks/issues/71
https://github.com/canonical/kserve-rocks/issues/72
https://github.com/canonical/kserve-rocks/issues/73
https://github.com/canonical/kserve-rocks/issues/74
Rocks integration PR. Tested also locally by deploying and checking the serving for all of the servers by deploying the serving runtimes.
> Integrate rocks 0.13.0

- charms/kserve-controller/requirements-unit.txt
- charms/kserve-controller/requirements.txt
Part of canonical/bundle-kubeflow#883
> build: bump jinja2 3.1.x -> 3.1.4 (#256)

- charms/kserve-controller/src/default-custom-images.json
- charms/kserve-controller/tests/integration/config-map-data-changed.yaml
- charms/kserve-controller/tests/integration/config-map-data.yaml
backports #276 to `track/0.13`
> fix: integrate `kserve-agent` rock with patch (#276)

- charms/kserve-controller/charmcraft.yaml
Ref canonical/bundle-kubeflow#1178
> build: Enable building rust dependencies

- charms/kserve-controller/lib/charms/loki_k8s/v1/loki_push_api.py
- charms/kserve-controller/lib/charms/observability_libs/v1/kubernetes_service_patch.py
* Bump libraries using charmcraft fetch-lib.
* Check for major versions using noctua charm libraries check --major. If there is one, then commit a do-not-merge-message.txt file.
Ref canonical/bundle-kubeflow#1184
> chore: bump libraries

- charms/kserve-controller/metadata.yaml
Closes: https://warthogs.atlassian.net/browse/KF-6948
> chore: integrate `kserve-controller:0.14.1` rock

- charms/kserve-controller/src/default-custom-images.json
- charms/kserve-controller/tests/integration/config-map-data-changed.yaml
- charms/kserve-controller/tests/integration/config-map-data.yaml
Closes: https://warthogs.atlassian.net/browse/KF-6947
> chore: integrate kserve-agent:0.14.1 rock

- charms/kserve-controller/src/default-custom-images.json
- charms/kserve-controller/tests/integration/config-map-data-changed.yaml
- charms/kserve-controller/tests/integration/config-map-data.yaml
Close https://warthogs.atlassian.net/browse/KF-6991
> chore: integrate artexplainer rock for 0.14.1

- charms/kserve-controller/src/default-custom-images.json
Closes: https://warthogs.atlassian.net/browse/KF-6967
> chore: integrate `xgbserver:0.14.1` rock

- charms/kserve-controller/metadata.yaml
Closes https://github.com/canonical/kserve-operators/issues/328
Follow-up of https://github.com/canonical/kserve-rocks/pull/125
> feat: Update rock to not set readOnlyRootFilesystem

- charms/kserve-controller/metadata.yaml
- charms/kserve-controller/src/default-custom-images.json
- charms/kserve-controller/tests/integration/config-map-data-changed.yaml
- charms/kserve-controller/tests/integration/config-map-data.yaml
Ref #326 
Backport of  #331 and #329 to `track/0.14`
> backport: Integrate `router` rock

- charms/kserve-controller/terraform/variables.tf
- charms/kserve-controller/terraform/versions.tf
Cutting new release for branch track/0.14
> [KF-7254] Release 1.10

- charms/kserve-controller/terraform/variables.tf
> [KF-7268] chore: pin channel to latest/edge

- .github/workflows/integrate.yaml
- .github/workflows/tiobe_scan.yml
- charms/kserve-controller/tox.ini
- tox.ini
Updating with TIOBE scan, including:
* reformatting tox.ini file to be machine-generated and handled
* coverage.xml generation when running unit tests 
* creating tiobe_scan.yaml file
> [KF-7281] Enabling TIOBE scan

- charms/kserve-controller/src/default-custom-images.json
> Integrate rock for torchserve-kfs

- charms/kserve-controller/src/charm.py
Closes https://github.com/canonical/kserve-operators/issues/338
Update the error handling logic to better handle:
1. `connect: connection refused` and `connect: operation not permitted` errors, which have `connect: ` in common
2. there is a 500 error
To better describe the scenario of errors talking to the webhook, since the status code is the same.
> fix: handle operation-not-permitted error of webhook

- charms/kserve-controller/src/charm.py
Backports the fix of #338 into `track/0.14` branch
Update the error handling logic to better handle:
1. `connect: connection refused` and `connect: operation not permitted` errors, which have `connect: ` in common
2. there is a 500 error
To better describe the scenario of errors talking to the webhook, since the status code is the same.
> (backport)fix: handle operation-not-permitted error of webhook (#348)
